### ISSUE TITLE
Debugging tools

### ISSUE THREAD

**Issue by fleskesvor** [Double-Fine-Game-Club/amnesia-adventure#10]
A debug menu would be nice to have to quickly switch between rooms, verify that they load with the correct flags set, etc. 

A special room for testing playable characters with animations, items, inventory, etc. could also be pretty handy.

**Comment by JenniBee** [comment]
The Forum Downtime Funtime Adventure had a test room that wasn't hooked up to anything, and it definitely was quite helpful during development.  I'll create a test room in the skeleton engine and upload it in a bit (if you want to test or edit using the test room, simply change the game/game.esc file to point to test.scn).  Right now the main room uses the name test, but I'll simply clone that to room1 to have an unconnected test room that we can mess with if we need to try things without breaking the room code.

I'll look into setting up a debug menu, as I'm not quite sure if that's available in Godot - if push comes to shove, we can always make a custom debug menu for what we need using Godot's menu creation system.

**Comment by JenniBee** [comment]
Closing this, as Escoria's test scene was added in dd1f9533
