### ISSUE TITLE
Fix the popup when quitting in the menu

### ISSUE THREAD

**Issue by JenniBee** [Double-Fine-Game-Club/amnesia-adventure#11]
Cheeseness mentioned in IRC that confirm_popup.tscn is missing, which is breaking the quit button, so that needs to be addressed.

**Comment by JenniBee** [comment]
Since this was a major issue, I put up a fix that will quit when the quit button is pressed.  I'm going to leave this PR open though, as it would be nice to have the aforementioned popup ask whether you were sure you wanted to quit when you clicked the button.

The confirm_popup.tscn file is missing from the Escoria repository, so a replacement would have to be coded for this functionality.  Though, since quitting works fine now, this functionality isn't essential.

**Comment by Cheeseness** [comment]
it looks like confirm_popup.tscn is also used when starting a new game (presumably when there's a game already in progress).

**Comment by JenniBee** [comment]
Closing this as it was fixed in #29 and #36
