### ISSUE TITLE
Improve positioning of hud tooltip

### ISSUE THREAD

**Issue by fleskesvor** [Double-Fine-Game-Club/amnesia-adventure#13]
The hud tooltip is the text that appears when you hover your mouse over an item. This is a text label, which is an instance of the hud node, but its position is fixed, so text doesn't appear next to the item or mouse pointer like one might expect.

If it isn't too much work, we might look into updating the position from within game.gd on the mouse_enter event. We also need to consider the width of the label, however, since otherwise text might appear partially outside of the screen when examining items close to the edges of the screen.

This fix should also be submitted as a PR to Escoria.

**Comment by JenniBee** [comment]
I'm closing this, as it was addressed in #12
