### ISSUE TITLE
Sluggish confirm dialogue 

### ISSUE THREAD

**Issue by fleskesvor** [Double-Fine-Game-Club/amnesia-adventure#30]
The confirm dialogue seems to be a bit unresponsive, ie. the dialogue remains on-screen for a second or two after pressing an option until it goes away. Figure out what's causing this behavior. 

See https://github.com/Double-Fine-Game-Club/amnesia-adventure/pull/29

**Comment by JenniBee** [comment]
Closing this as this has been fixed in #36
