### ISSUE TITLE
Creative Consolidation

### ISSUE THREAD

**Issue by ghost** [Double-Fine-Game-Club/amnesia-adventure#44]
I really loved the potential of this being somewhat provoking around the issue of alzhiemers and dementia in order to build a character. Thinking of someone who I had the pleasure of care taking for who had an extrordinary life, record breaking doctor, ww2 navigator/pilot, hindenburg witness, alcapone, so many women it'd make leisure suit larry drool, our elders have had increadable lives and are loosing the last connections to a gone by reality.

Would I beable to find some support in making a commitment to a dark humor theme and storyline? Input, suggestions? I'll try to quantify the suggestions from the thread as a follow up to this.

**Comment by ghost** [comment]
Atleast as a fork of the initial project, anyone interested in following this?

I'm thinking there is the background and scene of the present day and through interaction overwriting the scene with a transition to the past. I want to touch upon the change of priority in getting through the day as memories take there final course. You lose the ability to remember what things are or are moved into a memory, and perception of reality and time become distorted as you hold onto who you are while you must continue functioning.

I think that a retirement home maybe too blunt, perhaps someone alone not wanting to be taken into medical custody. Family? Characters?

**Comment by fleskesvor** [comment]
Do you mean as a standalone scene or are you suggesting a change in tone and storyline for the entire game?

If it's the former, I don't see any problems with that, as long as it's in line with the family friendly style we've been aiming for with the other scenes.

If the latter, I think it's something we should discuss on the forums, where other contributors are more likely to see it. This might be an appropriate thread:

https://forums.doublefine.com/topic/17214-amnesia-adventure-concept-brainstorming/

The hub is currently pretty bare-bones, so it would be great to add some story content to it. And I'd be happy to help you with that, if needed.

**Comment by ghost** [comment]
Using this as proof of implimentation and taking the amnesia theme to a cohesive story that rewards replay with branching endings. So far I have only an idea to rewarding categories that shape the past of your elderly person based upon how you interact with your enviroment. And it would be fitting to hub it however large should you be continuing to develop it as a hub.

I destinctly remember asking myself, am I really trying to pixelate elderly people, one late night after finding the forum post. I'm not entirely sure of the options artisticly. Having to check items in specific orders and combinations to trigger memories feels interesting to my former (I did something) now I need to consult every NPC and location to see if I changed anything- play style.

I'll certainly post to the forum, thank you.

**Comment by ghost** [comment]
Eventually.
