### ISSUE TITLE
Missing dependencies - unable to load test scene

### ISSUE THREAD

**Issue by fleskesvor** [Double-Fine-Game-Club/amnesia-adventure#8]
The file game/inventory_items.scn fails to load because of missing dependencies. This is caused by several instances of TextureButton nodes which points to .png files which do not exist within the project.

Removing these nodes, the test scene still fails to load for me with the following error thrown:

`Attempt to call function 'replace_by_instance' in base 'null instance' on a null instance.`

Comparing to the original test scene in the Escoria framework, the CanvasLayer which has an instance of the hud scene appears to be missing from globals/game.scn, but re-attaching those throws a similar error:

`Invalid call. Nonexistent function 'replace_by_instance' in base 'Control (hud.gd)'.`

I am, however, able to load the test scene by pressing "Continue" from the debugger, and I can see the hud, but I'm unable to check if there are any features missing that may be caused by these issues.

I'm using version v2.1.2.stable.official of Godot on Linux.

**Comment by JenniBee** [comment]
I added my room to a clean build of Escoria, and Cheeseness confirmed that it builds and runs now.  However, Escoria itself has non-critical errors, so I'm going to keep this PR open until we manage to swat all these bugs.

**Comment by Cheeseness** [comment]
I feel like we should close this issue as its description misrepresents the current state of the repo. We can open additional issues for resolving specific problems with missing assets, etc.

**Comment by JenniBee** [comment]
I'll close this, as most of them have been zapped by now.
